<a href="https://colab.research.google.com/github/mehraanjali/HomePricePredictionUsingMultipleLinearRegression/blob/main/HomePricePredictionUsingMultipleLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

**To fill missing value with median value**

In [ ]:
df.bedrooms.median()

4.0

*incase if it would be in decimals so to round it off*

*import math*

*math.floor(df.bedrooms.median()*

In [ ]:
median = df.bedrooms.median()

In [ ]:
df.bedrooms.fillna(median)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

**To save these values in original dataset**

In [ ]:
df.bedrooms = df.bedrooms.fillna(median)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
from sklearn import linear_model

reg = linear_model.LinearRegression()

In [ ]:
reg.fit(df[['area',	'bedrooms',	'age']], df.price)

LinearRegression()

In [ ]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
reg.intercept_

221323.00186540396

In [ ]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [ ]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])